### ISSUE TITLE
启动后只能执行一次，之后报错

### ISSUE THREAD

**Issue by Jorfei8** [5high/Home-Assistant-Addons#1]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun aliyunbackup (no readiness notification)
s6-rc: info: service legacy-services successfully started
[09:22:34] INFO: 计划备份时间:03:00:00
[09:22:34] INFO: 云端备份保留数量:3
[09:22:34] INFO: 本地备份保留数量:7
[09:22:34] INFO: 正在启动阿里云盘备份 ...
2024-03-09 09:22:38 Checking Internet Connection ... 
2024-03-09 09:22:38 Staring Home Assistant Aliyun Backup ... 
2024-03-09 09:22:39 Login success ... 
2024-03-09 09:22:39 Checking available space...
2024-03-09 09:22:41 Backup folder exsist ... 
2024-03-09 09:22:41 Serve Http protal  ... 
2024-03-10 03:00:37 Starting backup and upload process ... 
2024-03-10 03:00:37 Full backup complet staring upload process ... 

  0%|          | 0.00/137M [00:00<?, ?B/s]
  8%|▊         | 10.5M/137M [00:01<00:15, 8.28MB/s]
 15%|█▌        | 21.0M/137M [00:02<00:12, 9.14MB/s]
 23%|██▎       | 31.5M/137M [00:03<00:11, 9.42MB/s]
 31%|███       | 41.9M/137M [00:04<00:09, 9.58MB/s]
 38%|███▊      | 52.4M/137M [00:06<00:11, 7.14MB/s]
 46%|████▌     | 62.9M/137M [00:07<00:09, 7.85MB/s]
 53%|█████▎    | 73.4M/137M [00:08<00:07, 8.42MB/s]
 61%|██████    | 83.9M/137M [00:09<00:06, 8.85MB/s]
 69%|██████▊   | 94.4M/137M [00:11<00:05, 8.23MB/s]
 76%|███████▋  | 105M/137M [00:12<00:04, 7.79MB/s] 
 84%|████████▍ | 115M/137M [00:14<00:02, 7.97MB/s]
 92%|█████████▏| 126M/137M [00:15<00:01, 8.00MB/s]
 99%|█████████▉| 136M/137M [00:16<00:00, 7.66MB/s]
100%|██████████| 137M/137M [00:17<00:00, 7.55MB/s]
100%|██████████| 137M/137M [00:17<00:00, 8.08MB/s]
Exception in thread schedule:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/bin/aligobk.py", line 593, in running_schedule
    schedule.run_pending()
  File "/usr/lib/python3.9/site-packages/schedule/__init__.py", line 822, in run_pending
    default_scheduler.run_pending()
  File "/usr/lib/python3.9/site-packages/schedule/__init__.py", line 100, in run_pending
    self._run_job(job)
  File "/usr/lib/python3.9/site-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/usr/lib/python3.9/site-packages/schedule/__init__.py", line 693, in run
    ret = self.job_func()
  File "/usr/bin/aligobk.py", line 580, in simulate_backup
    delete_expired()
  File "/usr/bin/aligobk.py", line 790, in delete_expired
    delete_local()
  File "/usr/bin/aligobk.py", line 782, in delete_local
    tobe_delete_local = filter_and_print_date(ls_local(),'slug',keep_days_local)
  File "/usr/bin/aligobk.py", line 743, in filter_and_print_date
    return to_print
UnboundLocalError: local variable 'to_print' referenced before assignment

**Comment by 5high** [comment]
升级最新版

**Comment by 5high** [comment]
已经修复
